/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.openbravo.pos.forms.bobview;

import java.awt.CardLayout;
import java.awt.Color;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.security.GeneralSecurityException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    private Restaurant rest;
    private Owner owner;
    private int leftnum = 0;
    private int resnum = 0;

    public LoginFrame() {

        initComponents();
        getContentPane().setBackground(Color.WHITE);
    }

    public void writeRestInfo() {
        FileWriter fw = null;
        try {
            File file = new File("restInfo");
            fw = new FileWriter(file);
            fw.write(owner.getRestaurant());
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fw.close();
            } catch (IOException ex) {
                Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    public boolean isSignIn() {
        if (owner == null) {
            return false;
        }
        return (!this.isVisible()) && owner.IsRegistered(); //  LoginFrame의 화면이 꺼지고 owner가 regist되어있으면 로그인 성공
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        mainPanel = new javax.swing.JPanel();
        login_Panel = new javax.swing.JPanel();
        register_button = new javax.swing.JButton();
        login_button = new javax.swing.JButton();
        login_PW = new javax.swing.JLabel();
        login_ID = new javax.swing.JLabel();
        login_ID_Text = new javax.swing.JTextField();
        login_PW_Text = new javax.swing.JPasswordField();
        logo1 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        register_Panel = new javax.swing.JPanel();
        register_Name = new javax.swing.JLabel();
        register_ID = new javax.swing.JLabel();
        register_PW = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        register_confirm = new javax.swing.JButton();
        register_Name_Text = new javax.swing.JTextField();
        register_ID_Text = new javax.swing.JTextField();
        register_PW_Text = new javax.swing.JPasswordField();
        register_Rest = new javax.swing.JLabel();
        register_Rest_Text = new javax.swing.JTextField();
        back_button = new javax.swing.JButton();
        logo3 = new javax.swing.JLabel();
        logo5 = new javax.swing.JLabel();
        shop_Panel1 = new javax.swing.JPanel();
        reservation_Check = new javax.swing.JCheckBox();
        left_seat_Check = new javax.swing.JCheckBox();
        food_type_Combo = new javax.swing.JComboBox<>();
        shop_Name = new javax.swing.JLabel();
        shop_Phone = new javax.swing.JLabel();
        shop_Address = new javax.swing.JLabel();
        shop_Name_Text = new javax.swing.JTextField();
        shop_Phone_Text = new javax.swing.JTextField();
        shop_Address_Text = new javax.swing.JTextField();
        shop1_title = new javax.swing.JLabel();
        shop1_next_button = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        logo4 = new javax.swing.JLabel();
        shop_Panel2 = new javax.swing.JPanel();
        shop2_title = new javax.swing.JLabel();
        shop2_label1 = new javax.swing.JLabel();
        shop2_label2 = new javax.swing.JLabel();
        shop2_Mon_check = new javax.swing.JCheckBox();
        shop2_Tue_check = new javax.swing.JCheckBox();
        shop2_Wen_check = new javax.swing.JCheckBox();
        shop2_Thr_check = new javax.swing.JCheckBox();
        shop2_Fri_check = new javax.swing.JCheckBox();
        shop2_Sat_check = new javax.swing.JCheckBox();
        shop2_Sun_check = new javax.swing.JCheckBox();
        shop2_label3 = new javax.swing.JLabel();
        shop2_Break_check = new javax.swing.JCheckBox();
        shop2_Break_Startbox = new javax.swing.JComboBox<>();
        shop2_Break_Endbox = new javax.swing.JComboBox<>();
        shop2_label4 = new javax.swing.JLabel();
        shop2_label5 = new javax.swing.JLabel();
        shop2_next_button = new javax.swing.JButton();
        shop2_label6 = new javax.swing.JLabel();
        shop2_hours_Box = new javax.swing.JComboBox<>();
        logo6 = new javax.swing.JLabel();
        shop_Panel3 = new javax.swing.JPanel();
        shop3_title = new javax.swing.JLabel();
        shop3_label1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        shop3_Mon_Start = new javax.swing.JComboBox<>();
        shop3_Mon_End = new javax.swing.JComboBox<>();
        shop3_Tue_Start = new javax.swing.JComboBox<>();
        shop3_Tue_End = new javax.swing.JComboBox<>();
        shop3_Wen_Start = new javax.swing.JComboBox<>();
        shop3_Wen_End = new javax.swing.JComboBox<>();
        shop3_Thr_Start = new javax.swing.JComboBox<>();
        shop3_Thr_End = new javax.swing.JComboBox<>();
        shop3_Fri_Start = new javax.swing.JComboBox<>();
        shop3_Fri_End = new javax.swing.JComboBox<>();
        shop3_Sat_Start = new javax.swing.JComboBox<>();
        shop3_Sat_End = new javax.swing.JComboBox<>();
        shop3_Sun_Start = new javax.swing.JComboBox<>();
        shop3_Sun_End = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        logo7 = new javax.swing.JLabel();
        shop_Panel4 = new javax.swing.JPanel();
        shop4_title1 = new javax.swing.JLabel();
        shop4_label2 = new javax.swing.JLabel();
        shop4_label3 = new javax.swing.JLabel();
        shop4_label4 = new javax.swing.JLabel();
        shop4_label5 = new javax.swing.JLabel();
        shop4_label6 = new javax.swing.JLabel();
        shop4_label7 = new javax.swing.JLabel();
        shop4_All_Start = new javax.swing.JComboBox<>();
        shop4_All_End = new javax.swing.JComboBox<>();
        shop4_Weekday_Start = new javax.swing.JComboBox<>();
        shop4_Weekday_End = new javax.swing.JComboBox<>();
        shop4_Weekend_Start = new javax.swing.JComboBox<>();
        shop4_Weekend_End = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        logo8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(551, 700));
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(551, 700));
        mainPanel.setLayout(new java.awt.CardLayout());

        login_Panel.setBackground(new java.awt.Color(255, 255, 255));
        login_Panel.setPreferredSize(new java.awt.Dimension(551, 700));

        register_button.setBackground(new java.awt.Color(255, 255, 255));
        register_button.setFont(new java.awt.Font("휴먼편지체", 1, 35)); // NOI18N
        register_button.setForeground(new java.awt.Color(20,60,100));
        register_button.setText("회원가입");
        register_button.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        register_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        register_button.setMaximumSize(new java.awt.Dimension(71, 71));
        register_button.setMinimumSize(new java.awt.Dimension(71, 71));
        register_button.setPreferredSize(new java.awt.Dimension(71, 71));
        register_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_buttonActionPerformed(evt);
            }
        });

        login_button.setBackground(new java.awt.Color(255, 255, 255));
        login_button.setFont(new java.awt.Font("휴먼편지체", 1, 36)); // NOI18N
        login_button.setForeground(new java.awt.Color(20,60,100));
        login_button.setText("로그인");
        login_button.setToolTipText("");
        login_button.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        login_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    login_buttonActionPerformed(evt);
                } catch (GeneralSecurityException ex) {
                    Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedEncodingException ex) {
                    Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        login_PW.setBackground(new java.awt.Color(255, 255, 255));
        login_PW.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        login_PW.setForeground(new java.awt.Color(20,60,100));
        login_PW.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        login_PW.setText("PW");

        login_ID.setBackground(new java.awt.Color(255, 255, 255));
        login_ID.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        login_ID.setForeground(new java.awt.Color(20,60,100));
        login_ID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        login_ID.setText("ID");

        login_ID_Text.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        login_ID_Text.setForeground(new java.awt.Color(0, 0, 0));

        login_PW_Text.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        login_PW_Text.setForeground(new java.awt.Color(0, 0, 0));

        logo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/pos/forms/bobview/logo2.png"))); // NOI18N

        logo.setBackground(new java.awt.Color(204, 255, 204));
        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/pos/forms/bobview/logo.png"))); // NOI18N

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("HY헤드라인M", 1, 50)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(20, 45, 90));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Pos Login");

        javax.swing.GroupLayout login_PanelLayout = new javax.swing.GroupLayout(login_Panel);
        login_Panel.setLayout(login_PanelLayout);
        login_PanelLayout.setHorizontalGroup(
            login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
            .addComponent(logo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(login_PanelLayout.createSequentialGroup()
                .addGroup(login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(login_PW, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(login_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(login_ID_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(login_PanelLayout.createSequentialGroup()
                            .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(register_button, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(login_PW_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        login_PanelLayout.setVerticalGroup(
            login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addGap(35, 35, 35)
                .addComponent(logo1)
                .addGap(61, 61, 61)
                .addGroup(login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_ID_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_ID))
                .addGap(18, 18, 18)
                .addGroup(login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_PW)
                    .addComponent(login_PW_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(register_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        mainPanel.add(login_Panel, "card1");

        register_Panel.setBackground(new java.awt.Color(255, 255, 255));
        register_Panel.setForeground(new java.awt.Color(1, 0, 0));
        register_Panel.setPreferredSize(new java.awt.Dimension(551, 700));

        register_Name.setBackground(new java.awt.Color(255, 255, 255));
        register_Name.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        register_Name.setForeground(new java.awt.Color(20,60,100));
        register_Name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        register_Name.setText("이름");

        register_ID.setBackground(new java.awt.Color(255, 255, 255));
        register_ID.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        register_ID.setForeground(new java.awt.Color(20,60,100));
        register_ID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        register_ID.setText("ID");

        register_PW.setBackground(new java.awt.Color(255, 255, 255));
        register_PW.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        register_PW.setForeground(new java.awt.Color(20,60,100));
        register_PW.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        register_PW.setText("PW");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("HY헤드라인M", 1, 50)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(20,45,90));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("회원가입");

        register_confirm.setBackground(new java.awt.Color(255, 255, 255));
        register_confirm.setFont(new java.awt.Font("휴먼편지체", 1, 30)); // NOI18N
        register_confirm.setForeground(new java.awt.Color(20,60,100));
        register_confirm.setText("등록");
        register_confirm.setToolTipText("");
        register_confirm.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        register_confirm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        register_confirm.setMaximumSize(new java.awt.Dimension(65, 65));
        register_confirm.setMinimumSize(new java.awt.Dimension(65, 65));
        register_confirm.setPreferredSize(new java.awt.Dimension(65, 65));
        register_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_confirmActionPerformed(evt);
            }
        });

        back_button.setBackground(new java.awt.Color(255, 255, 255));
        back_button.setFont(new java.awt.Font("휴먼편지체", 1, 30)); // NOI18N
        back_button.setForeground(new java.awt.Color(20,60,100));
        back_button.setText("뒤로");
        back_button.setToolTipText("");
        back_button.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        back_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        register_Name_Text.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N

        register_ID_Text.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N

        register_PW_Text.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N

        register_Rest.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        register_Rest.setForeground(new java.awt.Color(20,60,100));
        register_Rest.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        register_Rest.setText("매장 이름");

        register_Rest_Text.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N

        logo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/pos/forms/bobview/logo.png"))); // NOI18N

        logo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/pos/forms/bobview/logo2.png"))); // NOI18N

        javax.swing.GroupLayout register_PanelLayout = new javax.swing.GroupLayout(register_Panel);
        register_Panel.setLayout(register_PanelLayout);
        register_PanelLayout.setHorizontalGroup(
            register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logo5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(register_PanelLayout.createSequentialGroup()
                .addGroup(register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(register_Rest, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(register_PW, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(register_ID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(register_Name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(register_PW_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(register_Rest_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(register_Name_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(register_ID_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(register_PanelLayout.createSequentialGroup()
                        .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(register_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        register_PanelLayout.setVerticalGroup(
            register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(register_PanelLayout.createSequentialGroup()
                .addComponent(logo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(logo5)
                .addGap(18, 18, 18)
                .addGroup(register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(register_ID_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(register_Name))
                .addGap(18, 18, 18)
                .addGroup(register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(register_ID)
                    .addComponent(register_Name_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(register_PW)
                    .addComponent(register_PW_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(register_Rest)
                    .addComponent(register_Rest_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(register_confirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        mainPanel.add(register_Panel, "card2");

        /*
        shop_Panel1.setBackground(new java.awt.Color(255, 255, 255));
        shop_Panel1.setPreferredSize(new java.awt.Dimension(551, 700));

        reservation_Check.setBackground(new java.awt.Color(255, 255, 255));
        reservation_Check.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        reservation_Check.setForeground(new java.awt.Color(153, 153, 0));
        reservation_Check.setText("예약");
        reservation_Check.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                reservation_CheckItemStateChanged(evt);
            }
        });

        left_seat_Check.setBackground(new java.awt.Color(255, 255, 255));
        left_seat_Check.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        left_seat_Check.setForeground(new java.awt.Color(153, 153, 0));
        left_seat_Check.setText("잔여좌석");
        left_seat_Check.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                left_seat_CheckItemStateChanged(evt);
            }
        });

        food_type_Combo.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        food_type_Combo.setForeground(new java.awt.Color(153, 153, 0));
        food_type_Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "한식", "중식", "일식", "양식" }));
        food_type_Combo.setFocusable(false);

        shop_Name.setBackground(new java.awt.Color(255, 255, 255));
        shop_Name.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop_Name.setForeground(new java.awt.Color(153, 153, 0));
        shop_Name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        shop_Name.setText("매장 이름");

        shop_Phone.setBackground(new java.awt.Color(255, 255, 255));
        shop_Phone.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop_Phone.setForeground(new java.awt.Color(153, 153, 0));
        shop_Phone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        shop_Phone.setText("매장 전화번호");

        shop_Address.setBackground(new java.awt.Color(255, 255, 255));
        shop_Address.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop_Address.setForeground(new java.awt.Color(153, 153, 0));
        shop_Address.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        shop_Address.setText("매장 주소");

        shop_Name_Text.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N

        shop_Phone_Text.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N

        shop_Address_Text.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N

        shop1_title.setBackground(new java.awt.Color(255, 255, 255));
        shop1_title.setFont(new java.awt.Font("휴먼편지체", 1, 36)); // NOI18N
        shop1_title.setForeground(new java.awt.Color(153, 153, 0));
        shop1_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shop1_title.setText("매장 정보 입력");
        shop1_title.setToolTipText("");

        shop1_next_button.setBackground(new java.awt.Color(255, 255, 255));
        shop1_next_button.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop1_next_button.setForeground(new java.awt.Color(153, 153, 0));
        shop1_next_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/pos/forms/bobview/arrows.png"))); // NOI18N
        shop1_next_button.setText("다음");
        shop1_next_button.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        shop1_next_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        shop1_next_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shop1_next_buttonActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("점주 공지");

        jTextField1.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 153, 0));
        jButton3.setText("불러오기");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("매장 이미지");
        jLabel10.setToolTipText("");

        logo4.setBackground(new java.awt.Color(204, 255, 204));
        logo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/pos/forms/bobview/logo.png"))); // NOI18N

        javax.swing.GroupLayout shop_Panel1Layout = new javax.swing.GroupLayout(shop_Panel1);
        shop_Panel1.setLayout(shop_Panel1Layout);
        shop_Panel1Layout.setHorizontalGroup(
            shop_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(shop1_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(shop_Panel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(shop_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(shop_Panel1Layout.createSequentialGroup()
                        .addGroup(shop_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(shop_Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(shop_Phone, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(shop_Address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(shop_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(shop_Phone_Text)
                            .addComponent(shop_Address_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shop_Name_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shop_Panel1Layout.createSequentialGroup()
                        .addGroup(shop_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(left_seat_Check)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(shop_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shop1_next_button)
                            .addGroup(shop_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(shop_Panel1Layout.createSequentialGroup()
                                    .addComponent(reservation_Check)
                                    .addGap(18, 18, 18)
                                    .addGroup(shop_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(food_type_Combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addGap(100, 100, 100))
            .addComponent(logo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        shop_Panel1Layout.setVerticalGroup(
            shop_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shop_Panel1Layout.createSequentialGroup()
                .addComponent(logo4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shop1_title)
                .addGap(61, 61, 61)
                .addGroup(shop_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shop_Name)
                    .addComponent(shop_Name_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(shop_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shop_Phone)
                    .addComponent(shop_Phone_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(shop_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shop_Address)
                    .addComponent(shop_Address_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(shop_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(shop_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(shop_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(left_seat_Check)
                        .addComponent(reservation_Check))
                    .addComponent(food_type_Combo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(shop_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(shop1_next_button)
                .addGap(68, 68, 68))
        );

        mainPanel.add(shop_Panel1, "card3");

        shop_Panel2.setBackground(new java.awt.Color(255, 255, 255));
        shop_Panel2.setPreferredSize(new java.awt.Dimension(551, 700));

        shop2_title.setFont(new java.awt.Font("휴먼편지체", 1, 36)); // NOI18N
        shop2_title.setForeground(new java.awt.Color(153, 153, 0));
        shop2_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shop2_title.setText("매장 정보 입력");

        shop2_label1.setFont(new java.awt.Font("휴먼편지체", 1, 24)); // NOI18N
        shop2_label1.setForeground(new java.awt.Color(153, 153, 0));
        shop2_label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shop2_label1.setText("영업시간");

        shop2_label2.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop2_label2.setForeground(new java.awt.Color(153, 153, 0));
        shop2_label2.setText("휴일을 선택하세요");

        shop2_Mon_check.setBackground(new java.awt.Color(255, 255, 255));
        shop2_Mon_check.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop2_Mon_check.setForeground(new java.awt.Color(153, 153, 0));
        shop2_Mon_check.setText("월");
        shop2_Mon_check.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                shop2_Mon_checkItemStateChanged(evt);
            }
        });

        shop2_Tue_check.setBackground(new java.awt.Color(255, 255, 255));
        shop2_Tue_check.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop2_Tue_check.setForeground(new java.awt.Color(153, 153, 0));
        shop2_Tue_check.setText("화");
        shop2_Tue_check.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                shop2_Tue_checkItemStateChanged(evt);
            }
        });

        shop2_Wen_check.setBackground(new java.awt.Color(255, 255, 255));
        shop2_Wen_check.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop2_Wen_check.setForeground(new java.awt.Color(153, 153, 0));
        shop2_Wen_check.setText("수");
        shop2_Wen_check.setToolTipText("");
        shop2_Wen_check.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                shop2_Wen_checkItemStateChanged(evt);
            }
        });

        shop2_Thr_check.setBackground(new java.awt.Color(255, 255, 255));
        shop2_Thr_check.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop2_Thr_check.setForeground(new java.awt.Color(153, 153, 0));
        shop2_Thr_check.setText("목");
        shop2_Thr_check.setToolTipText("");
        shop2_Thr_check.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                shop2_Thr_checkItemStateChanged(evt);
            }
        });

        shop2_Fri_check.setBackground(new java.awt.Color(255, 255, 255));
        shop2_Fri_check.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop2_Fri_check.setForeground(new java.awt.Color(153, 153, 0));
        shop2_Fri_check.setText("금");
        shop2_Fri_check.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                shop2_Fri_checkItemStateChanged(evt);
            }
        });

        shop2_Sat_check.setBackground(new java.awt.Color(255, 255, 255));
        shop2_Sat_check.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop2_Sat_check.setForeground(new java.awt.Color(153, 153, 0));
        shop2_Sat_check.setText("토");
        shop2_Sat_check.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                shop2_Sat_checkItemStateChanged(evt);
            }
        });

        shop2_Sun_check.setBackground(new java.awt.Color(255, 255, 255));
        shop2_Sun_check.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop2_Sun_check.setForeground(new java.awt.Color(153, 153, 0));
        shop2_Sun_check.setText("일");
        shop2_Sun_check.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                shop2_Sun_checkItemStateChanged(evt);
            }
        });

        shop2_label3.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop2_label3.setForeground(new java.awt.Color(153, 153, 0));
        shop2_label3.setText("Break 유무를 선택하세요");

        shop2_Break_check.setBackground(new java.awt.Color(255, 255, 255));
        shop2_Break_check.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop2_Break_check.setForeground(new java.awt.Color(153, 153, 0));
        shop2_Break_check.setText("Break");
        shop2_Break_check.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                shop2_Break_checkItemStateChanged(evt);
            }
        });

        shop2_Break_Startbox.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop2_Break_Startbox.setForeground(new java.awt.Color(153, 153, 0));
        shop2_Break_Startbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));
        shop2_Break_Startbox.setToolTipText("");
        shop2_Break_Startbox.setEnabled(false);

        shop2_Break_Endbox.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop2_Break_Endbox.setForeground(new java.awt.Color(153, 153, 0));
        shop2_Break_Endbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));
        shop2_Break_Endbox.setEnabled(false);

        shop2_label4.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop2_label4.setForeground(new java.awt.Color(153, 153, 0));
        shop2_label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shop2_label4.setText("~");

        shop2_label5.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop2_label5.setForeground(new java.awt.Color(153, 153, 0));
        shop2_label5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shop2_label5.setText("Break time");

        shop2_next_button.setBackground(new java.awt.Color(255, 255, 255));
        shop2_next_button.setFont(new java.awt.Font("휴먼편지체", 1, 24)); // NOI18N
        shop2_next_button.setForeground(new java.awt.Color(153, 153, 0));
        shop2_next_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/pos/forms/bobview/arrows.png"))); // NOI18N
        shop2_next_button.setText("다음");
        shop2_next_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        shop2_next_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shop2_next_buttonActionPerformed(evt);
            }
        });

        shop2_label6.setBackground(new java.awt.Color(255, 255, 255));
        shop2_label6.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop2_label6.setForeground(new java.awt.Color(153, 153, 0));
        shop2_label6.setText("영업시간(요일)");

        shop2_hours_Box.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop2_hours_Box.setForeground(new java.awt.Color(153, 153, 0));
        shop2_hours_Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "모든 시간 상이", "모든 시간 동일", "평일/주말" }));

        logo6.setBackground(new java.awt.Color(204, 255, 204));
        logo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/pos/forms/bobview/logo.png"))); // NOI18N

        javax.swing.GroupLayout shop_Panel2Layout = new javax.swing.GroupLayout(shop_Panel2);
        shop_Panel2.setLayout(shop_Panel2Layout);
        shop_Panel2Layout.setHorizontalGroup(
            shop_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(shop2_title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(shop2_label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(shop_Panel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(shop_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shop2_label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(shop_Panel2Layout.createSequentialGroup()
                        .addGroup(shop_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(shop_Panel2Layout.createSequentialGroup()
                                .addComponent(shop2_Mon_check)
                                .addGap(18, 18, 18)
                                .addComponent(shop2_Tue_check)
                                .addGap(18, 18, 18)
                                .addComponent(shop2_Wen_check)
                                .addGap(18, 18, 18)
                                .addComponent(shop2_Thr_check)
                                .addGap(18, 18, 18)
                                .addGroup(shop_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(shop_Panel2Layout.createSequentialGroup()
                                        .addComponent(shop2_Fri_check)
                                        .addGap(18, 18, 18)
                                        .addComponent(shop2_Sat_check))
                                    .addComponent(shop2_Break_check))
                                .addGap(18, 18, 18)
                                .addComponent(shop2_Sun_check))
                            .addComponent(shop2_label3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(shop_Panel2Layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(shop2_Break_Startbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(shop2_label4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(shop2_Break_Endbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(shop_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(shop2_next_button)
                                .addGroup(shop_Panel2Layout.createSequentialGroup()
                                    .addComponent(shop2_label6)
                                    .addGap(30, 30, 30)
                                    .addComponent(shop2_hours_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 100, Short.MAX_VALUE))
                    .addComponent(shop2_label5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(logo6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        shop_Panel2Layout.setVerticalGroup(
            shop_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shop_Panel2Layout.createSequentialGroup()
                .addComponent(logo6)
                .addGap(13, 13, 13)
                .addComponent(shop2_title)
                .addGap(18, 18, 18)
                .addComponent(shop2_label1)
                .addGap(18, 18, 18)
                .addComponent(shop2_label2)
                .addGap(18, 18, 18)
                .addGroup(shop_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shop2_Wen_check)
                    .addComponent(shop2_Thr_check)
                    .addComponent(shop2_Fri_check)
                    .addComponent(shop2_Sat_check)
                    .addComponent(shop2_Tue_check)
                    .addComponent(shop2_Sun_check)
                    .addComponent(shop2_Mon_check))
                .addGap(18, 18, 18)
                .addGroup(shop_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shop2_label3)
                    .addComponent(shop2_Break_check))
                .addGap(18, 18, 18)
                .addComponent(shop2_label5)
                .addGap(18, 18, 18)
                .addGroup(shop_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shop2_Break_Startbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop2_Break_Endbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop2_label4))
                .addGap(18, 18, 18)
                .addGroup(shop_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shop2_label6)
                    .addComponent(shop2_hours_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(shop2_next_button)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        mainPanel.add(shop_Panel2, "card4");

        shop_Panel3.setBackground(new java.awt.Color(255, 255, 255));
        shop_Panel3.setPreferredSize(new java.awt.Dimension(551, 700));

        shop3_title.setFont(new java.awt.Font("굴림", 1, 36)); // NOI18N
        shop3_title.setForeground(new java.awt.Color(153, 153, 0));
        shop3_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shop3_title.setText("매장 정보 입력");

        shop3_label1.setFont(new java.awt.Font("휴먼편지체", 1, 24)); // NOI18N
        shop3_label1.setForeground(new java.awt.Color(153, 153, 0));
        shop3_label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shop3_label1.setText("영업시간");

        jLabel1.setFont(new java.awt.Font("휴먼편지체", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 0));
        jLabel1.setText("월");

        jLabel2.setFont(new java.awt.Font("휴먼편지체", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 0));
        jLabel2.setText("화");

        jLabel3.setFont(new java.awt.Font("휴먼편지체", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 0));
        jLabel3.setText("수");

        jLabel4.setFont(new java.awt.Font("휴먼편지체", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 0));
        jLabel4.setText("목");

        jLabel5.setFont(new java.awt.Font("휴먼편지체", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 0));
        jLabel5.setText("금");

        jLabel6.setFont(new java.awt.Font("휴먼편지체", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 0));
        jLabel6.setText("토");

        jLabel7.setFont(new java.awt.Font("휴먼편지체", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 0));
        jLabel7.setText("일");

        jLabel8.setFont(new java.awt.Font("휴먼편지체", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("요일           시작        ~       종료");

        shop3_Mon_Start.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop3_Mon_Start.setForeground(new java.awt.Color(153, 153, 0));
        shop3_Mon_Start.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        shop3_Mon_End.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop3_Mon_End.setForeground(new java.awt.Color(153, 153, 0));
        shop3_Mon_End.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        shop3_Tue_Start.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop3_Tue_Start.setForeground(new java.awt.Color(153, 153, 0));
        shop3_Tue_Start.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        shop3_Tue_End.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop3_Tue_End.setForeground(new java.awt.Color(153, 153, 0));
        shop3_Tue_End.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        shop3_Wen_Start.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop3_Wen_Start.setForeground(new java.awt.Color(153, 153, 0));
        shop3_Wen_Start.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        shop3_Wen_End.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop3_Wen_End.setForeground(new java.awt.Color(153, 153, 0));
        shop3_Wen_End.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        shop3_Thr_Start.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop3_Thr_Start.setForeground(new java.awt.Color(153, 153, 0));
        shop3_Thr_Start.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        shop3_Thr_End.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop3_Thr_End.setForeground(new java.awt.Color(153, 153, 0));
        shop3_Thr_End.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        shop3_Fri_Start.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop3_Fri_Start.setForeground(new java.awt.Color(153, 153, 0));
        shop3_Fri_Start.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        shop3_Fri_End.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop3_Fri_End.setForeground(new java.awt.Color(153, 153, 0));
        shop3_Fri_End.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        shop3_Sat_Start.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop3_Sat_Start.setForeground(new java.awt.Color(153, 153, 0));
        shop3_Sat_Start.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        shop3_Sat_End.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop3_Sat_End.setForeground(new java.awt.Color(153, 153, 0));
        shop3_Sat_End.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        shop3_Sun_Start.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop3_Sun_Start.setForeground(new java.awt.Color(153, 153, 0));
        shop3_Sun_Start.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        shop3_Sun_End.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop3_Sun_End.setForeground(new java.awt.Color(153, 153, 0));
        shop3_Sun_End.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("휴먼편지체", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 153, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/pos/forms/bobview/arrows.png"))); // NOI18N
        jButton1.setText("등록");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        logo7.setBackground(new java.awt.Color(204, 255, 204));
        logo7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/pos/forms/bobview/logo.png"))); // NOI18N

        javax.swing.GroupLayout shop_Panel3Layout = new javax.swing.GroupLayout(shop_Panel3);
        shop_Panel3.setLayout(shop_Panel3Layout);
        shop_Panel3Layout.setHorizontalGroup(
            shop_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shop_Panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shop3_title, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(shop_Panel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(shop_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(156, 156, 156)
                .addGroup(shop_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shop3_Mon_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop3_Tue_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop3_Wen_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop3_Thr_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop3_Fri_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop3_Sat_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop3_Sun_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(shop_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shop3_Mon_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop3_Tue_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop3_Wen_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop3_Thr_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop3_Fri_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop3_Sat_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop3_Sun_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
            .addGroup(shop_Panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shop3_label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(logo7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(shop_Panel3Layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        shop_Panel3Layout.setVerticalGroup(
            shop_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shop_Panel3Layout.createSequentialGroup()
                .addComponent(logo7)
                .addGap(4, 4, 4)
                .addComponent(shop3_title)
                .addGap(18, 18, 18)
                .addComponent(shop3_label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(shop_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(shop3_Mon_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop3_Mon_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(shop_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(shop3_Tue_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop3_Tue_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(shop_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(shop3_Wen_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop3_Wen_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(shop_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(shop3_Thr_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop3_Thr_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(shop_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(shop3_Fri_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop3_Fri_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(shop_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(shop3_Sat_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop3_Sat_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(shop_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(shop3_Sun_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop3_Sun_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        mainPanel.add(shop_Panel3, "card5");

        shop_Panel4.setBackground(new java.awt.Color(255, 255, 255));
        shop_Panel4.setPreferredSize(new java.awt.Dimension(551, 700));

        shop4_title1.setFont(new java.awt.Font("휴먼편지체", 1, 36)); // NOI18N
        shop4_title1.setForeground(new java.awt.Color(153, 153, 0));
        shop4_title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shop4_title1.setText("매장 정보 입력");

        shop4_label2.setFont(new java.awt.Font("휴먼편지체", 1, 24)); // NOI18N
        shop4_label2.setForeground(new java.awt.Color(153, 153, 0));
        shop4_label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shop4_label2.setText("영업시간");

        shop4_label3.setBackground(new java.awt.Color(255, 255, 255));
        shop4_label3.setFont(new java.awt.Font("휴먼편지체", 1, 24)); // NOI18N
        shop4_label3.setForeground(new java.awt.Color(153, 153, 0));
        shop4_label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shop4_label3.setText("모든 시간 동일");

        shop4_label4.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop4_label4.setForeground(new java.awt.Color(153, 153, 0));
        shop4_label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shop4_label4.setText("~");

        shop4_label5.setBackground(new java.awt.Color(255, 255, 255));
        shop4_label5.setFont(new java.awt.Font("휴먼편지체", 1, 24)); // NOI18N
        shop4_label5.setForeground(new java.awt.Color(153, 153, 0));
        shop4_label5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shop4_label5.setText("평일/주말");

        shop4_label6.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop4_label6.setForeground(new java.awt.Color(153, 153, 0));
        shop4_label6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shop4_label6.setText("~");

        shop4_label7.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop4_label7.setForeground(new java.awt.Color(153, 153, 0));
        shop4_label7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shop4_label7.setText("~");

        shop4_All_Start.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop4_All_Start.setForeground(new java.awt.Color(153, 153, 0));
        shop4_All_Start.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        shop4_All_End.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop4_All_End.setForeground(new java.awt.Color(153, 153, 0));
        shop4_All_End.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        shop4_Weekday_Start.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop4_Weekday_Start.setForeground(new java.awt.Color(153, 153, 0));
        shop4_Weekday_Start.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        shop4_Weekday_End.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop4_Weekday_End.setForeground(new java.awt.Color(153, 153, 0));
        shop4_Weekday_End.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        shop4_Weekend_Start.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop4_Weekend_Start.setForeground(new java.awt.Color(153, 153, 0));
        shop4_Weekend_Start.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        shop4_Weekend_End.setFont(new java.awt.Font("휴먼편지체", 1, 18)); // NOI18N
        shop4_Weekend_End.setForeground(new java.awt.Color(153, 153, 0));
        shop4_Weekend_End.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("휴먼편지체", 1, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 153, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/pos/forms/bobview/arrows.png"))); // NOI18N
        jButton2.setText("등록");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        logo8.setBackground(new java.awt.Color(204, 255, 204));
        logo8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/pos/forms/bobview/logo.png"))); // NOI18N

        javax.swing.GroupLayout shop_Panel4Layout = new javax.swing.GroupLayout(shop_Panel4);
        shop_Panel4.setLayout(shop_Panel4Layout);
        shop_Panel4Layout.setHorizontalGroup(
            shop_Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(shop4_label3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(shop4_label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shop_Panel4Layout.createSequentialGroup()
                .addComponent(shop4_title1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(logo8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(shop4_label5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shop_Panel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(shop4_All_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shop4_label4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shop4_All_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shop_Panel4Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(shop_Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(shop_Panel4Layout.createSequentialGroup()
                        .addComponent(shop4_Weekday_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shop4_label6, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                    .addGroup(shop_Panel4Layout.createSequentialGroup()
                        .addComponent(shop4_Weekend_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(shop_Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shop4_label7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shop_Panel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(15, 15, 15)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(shop_Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shop4_Weekday_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop4_Weekend_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(127, 127, 127))
        );
        shop_Panel4Layout.setVerticalGroup(
            shop_Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shop_Panel4Layout.createSequentialGroup()
                .addComponent(logo8)
                .addGap(18, 18, 18)
                .addComponent(shop4_title1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shop4_label2)
                .addGap(18, 18, 18)
                .addComponent(shop4_label3)
                .addGap(18, 18, 18)
                .addGroup(shop_Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shop4_All_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop4_All_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop4_label4))
                .addGap(47, 47, 47)
                .addComponent(shop4_label5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(shop_Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shop4_Weekday_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop4_Weekday_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop4_label6))
                .addGap(28, 28, 28)
                .addGroup(shop_Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shop4_Weekend_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop4_Weekend_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop4_label7))
                .addGap(37, 37, 37)
                .addComponent(jButton2)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        mainPanel.add(shop_Panel4, "card6");
         */                                        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents 

    private void register_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_confirmActionPerformed
        // TODO add your handling code here:
        if (register_ID_Text.getText().isEmpty() || register_Name_Text.getText().isEmpty() || register_PW_Text.getText().isEmpty() || register_Rest_Text.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "회원가입 실패", "알림 메시지", JOptionPane.INFORMATION_MESSAGE);
        } 
        else {
            RegistOwner registOwner = new RegistOwner(register_ID_Text.getText(), register_Name_Text.getText(), register_PW_Text.getText(), register_Rest_Text.getText());
            if (registOwner.regist()) {
                JOptionPane.showMessageDialog(null, "회원가입 완료", "알림 메시지", JOptionPane.INFORMATION_MESSAGE);
                CardLayout card = (CardLayout) mainPanel.getLayout();
                card.show(mainPanel, "card1");
            }
        }


    }//GEN-LAST:event_register_confirmActionPerformed

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) throws GeneralSecurityException, UnsupportedEncodingException {//GEN-FIRST:event_login_buttonActionPerformed
        // TODO add your handling code here:
        LoginOwner loginOwner = new LoginOwner(login_ID_Text.getText(), login_PW_Text.getText());
        rest = new Restaurant();
        owner = loginOwner.login();
        if (owner == null) {
            JOptionPane.showMessageDialog(null, "로그인 실패.", "오류 메시지", JOptionPane.ERROR_MESSAGE);
            System.out.println("로그인 실패");
        } else if (owner.IsRegistered()) {
            // 검증 후 dPos화면
            JOptionPane.showMessageDialog(null, "포스 시스템을 시작합니다.", "알림 메시지", JOptionPane.INFORMATION_MESSAGE);
            setVisible(false);
            dispose();
            System.out.println("포스 작동");
//            AddMenuInfo addMenuInfo = new AddMenuInfo();
//            addMenuInfo.sync();
        } else {
            JOptionPane.showMessageDialog(null, "식당이 등록되어 있지 않습니다.", "알림 메시지", JOptionPane.INFORMATION_MESSAGE);
            CardLayout card = (CardLayout) mainPanel.getLayout();
            card.show(mainPanel, "card2");
        }
    }//GEN-LAST:event_login_buttonActionPerformed

    private void register_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_buttonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "card2");
    }//GEN-LAST:event_register_buttonActionPerformed

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt){
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "card1");
       
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> food_type_Combo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JCheckBox left_seat_Check;
    private javax.swing.JLabel login_ID;
    private javax.swing.JTextField login_ID_Text;
    private javax.swing.JLabel login_PW;
    private javax.swing.JPasswordField login_PW_Text;
    private javax.swing.JPanel login_Panel;
    private javax.swing.JButton login_button;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo1;
    private javax.swing.JLabel logo3;
    private javax.swing.JLabel logo4;
    private javax.swing.JLabel logo5;
    private javax.swing.JLabel logo6;
    private javax.swing.JLabel logo7;
    private javax.swing.JLabel logo8;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel register_ID;
    private javax.swing.JTextField register_ID_Text;
    private javax.swing.JLabel register_Name;
    private javax.swing.JTextField register_Name_Text;
    private javax.swing.JLabel register_PW;
    private javax.swing.JPasswordField register_PW_Text;
    private javax.swing.JPanel register_Panel;
    private javax.swing.JLabel register_Rest;
    private javax.swing.JTextField register_Rest_Text;
    private javax.swing.JButton register_button;
    private javax.swing.JButton register_confirm;
    private javax.swing.JButton back_button;
    private javax.swing.JCheckBox reservation_Check;
    private javax.swing.JButton shop1_next_button;
    private javax.swing.JLabel shop1_title;
    private javax.swing.JComboBox<String> shop2_Break_Endbox;
    private javax.swing.JComboBox<String> shop2_Break_Startbox;
    private javax.swing.JCheckBox shop2_Break_check;
    private javax.swing.JCheckBox shop2_Fri_check;
    private javax.swing.JCheckBox shop2_Mon_check;
    private javax.swing.JCheckBox shop2_Sat_check;
    private javax.swing.JCheckBox shop2_Sun_check;
    private javax.swing.JCheckBox shop2_Thr_check;
    private javax.swing.JCheckBox shop2_Tue_check;
    private javax.swing.JCheckBox shop2_Wen_check;
    private javax.swing.JComboBox<String> shop2_hours_Box;
    private javax.swing.JLabel shop2_label1;
    private javax.swing.JLabel shop2_label2;
    private javax.swing.JLabel shop2_label3;
    private javax.swing.JLabel shop2_label4;
    private javax.swing.JLabel shop2_label5;
    private javax.swing.JLabel shop2_label6;
    private javax.swing.JButton shop2_next_button;
    private javax.swing.JLabel shop2_title;
    private javax.swing.JComboBox<String> shop3_Fri_End;
    private javax.swing.JComboBox<String> shop3_Fri_Start;
    private javax.swing.JComboBox<String> shop3_Mon_End;
    private javax.swing.JComboBox<String> shop3_Mon_Start;
    private javax.swing.JComboBox<String> shop3_Sat_End;
    private javax.swing.JComboBox<String> shop3_Sat_Start;
    private javax.swing.JComboBox<String> shop3_Sun_End;
    private javax.swing.JComboBox<String> shop3_Sun_Start;
    private javax.swing.JComboBox<String> shop3_Thr_End;
    private javax.swing.JComboBox<String> shop3_Thr_Start;
    private javax.swing.JComboBox<String> shop3_Tue_End;
    private javax.swing.JComboBox<String> shop3_Tue_Start;
    private javax.swing.JComboBox<String> shop3_Wen_End;
    private javax.swing.JComboBox<String> shop3_Wen_Start;
    private javax.swing.JLabel shop3_label1;
    private javax.swing.JLabel shop3_title;
    private javax.swing.JComboBox<String> shop4_All_End;
    private javax.swing.JComboBox<String> shop4_All_Start;
    private javax.swing.JComboBox<String> shop4_Weekday_End;
    private javax.swing.JComboBox<String> shop4_Weekday_Start;
    private javax.swing.JComboBox<String> shop4_Weekend_End;
    private javax.swing.JComboBox<String> shop4_Weekend_Start;
    private javax.swing.JLabel shop4_label2;
    private javax.swing.JLabel shop4_label3;
    private javax.swing.JLabel shop4_label4;
    private javax.swing.JLabel shop4_label5;
    private javax.swing.JLabel shop4_label6;
    private javax.swing.JLabel shop4_label7;
    private javax.swing.JLabel shop4_title1;
    private javax.swing.JLabel shop_Address;
    private javax.swing.JTextField shop_Address_Text;
    private javax.swing.JLabel shop_Name;
    private javax.swing.JTextField shop_Name_Text;
    private javax.swing.JPanel shop_Panel1;
    private javax.swing.JPanel shop_Panel2;
    private javax.swing.JPanel shop_Panel3;
    private javax.swing.JPanel shop_Panel4;
    private javax.swing.JLabel shop_Phone;
    private javax.swing.JTextField shop_Phone_Text;
    // End of variables declaration//GEN-END:variables
}
