# Generated by Django 2.2.6 on 2019-11-23 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QrImages',
        ),
    ]
