# Generated by Django 2.2.5 on 2019-10-14 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuRating',
            fields=[
                ('menu_rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.FloatField()),
                ('desc', models.TextField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.MenuInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'menu_rating',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderContents',
            fields=[
                ('order_contents_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_num', models.IntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.MenuInfo')),
            ],
            options={
                'db_table': 'order_contents',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RestRating',
            fields=[
                ('rest_rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.FloatField()),
                ('desc', models.TextField()),
            ],
            options={
                'db_table': 'rest_rating',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('user_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_time', models.DateTimeField()),
                ('tot_price', models.IntegerField()),
                ('table_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_order',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ordermenu',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='ordermenu',
            name='order',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderMenu',
        ),
        migrations.AddField(
            model_name='restrating',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.RestaurantInfo'),
        ),
        migrations.AddField(
            model_name='restrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordercontents',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.RestaurantInfo'),
        ),
        migrations.AddField(
            model_name='ordercontents',
            name='userorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.UserOrder'),
        ),
    ]
