# Generated by Django 2.2.6 on 2019-10-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191014_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantinfo',
            name='restaurant_address',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='restaurant_name',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
