# Generated by Django 2.2.6 on 2019-11-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_delete_qrimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('cocktail_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('alcoholic', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=30)),
                ('glass', models.CharField(max_length=30)),
                ('instruction', models.TextField()),
                ('drink_image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cocktail',
                'managed': True,
            },
        ),
    ]
