# Generated by Django 2.2.6 on 2019-10-29 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_imagetable'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='imagetable',
            table='image_table',
        ),
    ]
