# Generated by Django 2.2.6 on 2019-10-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191014_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantinfo',
            name='restaurant_address',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='restaurant_name',
            field=models.CharField(max_length=45, primary_key=True, serialize=False, unique=True),
        ),
    ]
