# Generated by Django 2.2.6 on 2019-11-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191030_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
