# Generated by Django 2.2.6 on 2019-11-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cocktail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='cocktail_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
