//    dPOS  - Dongwun Point Of Sale
//    Copyright (C) 2008-2009 Openbravo, S.L.
//    http://www.dongwun.com
//
//    This file is part of dPOS
//
//    dPOS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//   dPOS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with dPOS.  If not, see <http://www.gnu.org/licenses/>.

package com.openbravo.pos.payment;

import com.openbravo.pos.forms.AppConfig;
import com.openbravo.pos.forms.StartPOS;
import com.openbravo.pos.forms.AppLocal;
import javax.swing.JPanel;

/**
 *
 * @author  Dongwun
 */
public class ConfigPaymentPanelSerial extends javax.swing.JPanel implements PaymentConfiguration {
    private static final long serialVersionUID = 1874505755855066570L;

    /** Creates new form ConfigPaymentPanelGeneric */
    public ConfigPaymentPanelSerial() {
        initComponents();
    }
    
    /**
     *
     * @return
     */
    @Override
    public JPanel getComponent() {  
        return this;
    }
    
    /**
     *
     * @param config
     */
    @Override
    public void loadProperties(AppConfig config) {
        String sTerminalPort = config.getProperty("payment.terminalport");
        String sTerminalBPS = config.getProperty("payment.terminalbps");
        
        if (sTerminalPort != null && sTerminalBPS != null) {
            jtxtTerminalPort.setText(sTerminalPort);
            jtxtTerminalBPS.setText(sTerminalBPS);
        }
    }
    
    /**
     *
     * @param config
     */
    @Override
    public void saveProperties(AppConfig config) {
        config.setProperty("payment.terminalport", jtxtTerminalPort.getText());
        config.setProperty("payment.terminalbps", jtxtTerminalBPS.getText());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtTerminalPort = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtTerminalBPS = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(650, 75));

        jLabel1.setFont(StartPOS.getgblFont().deriveFont(0, 12));
        jLabel1.setText(AppLocal.getIntString("label.terminalport")); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(91, 30));

        jtxtTerminalPort.setFont(StartPOS.getgblFont().deriveFont(0, 12));
        jtxtTerminalPort.setPreferredSize(new java.awt.Dimension(91, 30));

        jLabel2.setFont(StartPOS.getgblFont().deriveFont(0, 12));
        jLabel2.setText(AppLocal.getIntString("label.terminalbps")); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 30));

        jtxtTerminalBPS.setFont(StartPOS.getgblFont().deriveFont(0, 12));
        jtxtTerminalBPS.setPreferredSize(new java.awt.Dimension(91, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtTerminalPort, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtTerminalBPS, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(360, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtTerminalPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtTerminalBPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jtxtTerminalBPS;
    private javax.swing.JTextField jtxtTerminalPort;
    // End of variables declaration//GEN-END:variables

}
